#it's work
version: "3"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
       - MYSQL_ROOT_PASSWORD=password
       - MYSQL_DATABASE=retrobox_api
    ports:
     - "3308:3306"
  api:
    build: .
    ports:
     - "80:80"
    depends_on:
      - db
    volumes:
      - .:/app
    links:
      - db
    environment:
       - APP_NAME=retrobox.api
       - APP_ENV_NAME=docker
       - APP_DEBUG=1
       - LOG_DISCORD=1
       - LOG_PATH=../log
       - LOG_LEVEL=INFO
       - LOG_DISCORD_WH=https://discordapp.com/api/webhooks/462292779348000771/-l9v1bnL78esX9VBx3MmwSOkcq1-Zii6j-05WHqSFIKSFSVa3b5MZR_-0unBevtuYwsA
       - MYSQL_HOST=db
       - MYSQL_DATABASE=retrobox_api
       - MYSQL_USERNAME=root
       - MYSQL_PASSWORD=password
       - STAILEU_PUBLIC=b28074ba-332f-47a9-b233-7c0ec17c5a26
       - STAILEU_PRIVATE=bd449255-a422-4d34-a385-45fb36ff75b9
       - STAILEU_REDIRECT=http://localhost:8000/account/execute
       - JWT_KEY=helloworldthisismyverysecurekey
       - SOURCE_DOMAIN=localhost
       - STRIPE_IS_TEST=1
       - STRIPE_PUBLIC=pk_test_vyGtkeybeUHvLZnXFbaHlXWC
       - STRIPE_PRIVATE=sk_test_CGzUzZDPACbTCb5m09gkoNKD
  adminer:
      image: adminer
      restart: always
      links:
        - db
      depends_on:
        - db
      ports:
        - "8080:8080"
