version: 2
jobs:
    build:
        steps:
        - setup_remote_docker
        - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - run: docker build -t retrobox/api .
        - run: docker push retrobox/api

